### PR TITLE
Proposed LOGGING.md documentation

### PR DESCRIPTION
**Pull request by biconou**
Guidelines for Contributing
---------------------------

Libresonic development is a community project, and contributions are welcomed. Here are a few guidelines you should follow before submitting:

  1.  **License Acceptance** All contributions must be licensed as [GNU GPLv3](https://github.com/Libresonic/libresonic/blob/develop/LICENSE.txt) to be accepted. Use [`git commit --signoff`](https://jk.gs/git-commit.html) to acknowledge this.
  2.  **No Breakage** New features or changes to existing ones must not degrade the user experience. This means do not introduce bugs, remove functionality, or make large changes to existing themes/UI without prior discussion in an Issue.
  3.  **Coding standards** Language best-practices should be followed, comment generously, and avoid "clever" algorithms. Refactoring existing messes is great, but watch out for breakage.
  4.  **Be bold!** Without contributions, this project will vanish. If you just want to help out, try [submiting a patch](https://github.com/Libresonic/libresonic/issues?q=is%3Aissue+is%3Aopen+label%3Apatches-welcome) for an open Issue.
  5.  **Stay relevant** Issues or commentary that is off-topic or tangential to Libresonic development is subject to moderation. Questions should be focused on improving documentation to solve a problem. Visit [Reddit](https://www.reddit.com/r/libresonic) or [IRC](http://webchat.freenode.net?channels=%23libresonic) for community discussion.

### CODE REVIEW

**Comment by muff1nman** [comment]
Isn't it easier by adding `-Dlogging.level.*` to the Java opts or even this parameter can be added to the libresonic properties file and it should work

**Comment by biconou** [comment]
Adding a java property on Java opts is is also interesting but it needs to change the command line.
I must confess I did not try to add logging level directives to the libresonic.properties file. I'll try it.

**Comment by biconou** [comment]
Putting log level directives in libresonic.properties file does not seem to work. 
@muff1nman did you test it ?

**Comment by muff1nman** [comment]
No I didn't. Just thought it might as they are also fed into the spring properties, but perhaps after the logging is setup.

The config folder thing is fine, but personally I feel that the java opts way is a bit simpler and should be the first method.

**Comment by jooola** [comment]
Could we merge this ? We need to build up the documentation repo and remove it from the software repo .
Or is this going in the dev docs ?

**Comment by biconou** [comment]
That's not dev doc but admin doc. 
I don't think it is ready to be merged as I should add documentation to configure logging through system properties as @muff1nman suggested.

**Comment by EugeneKay** [comment]
This looks like a great start. Please go ahead and push it to the new [documentation repository](https://github.com/Libresonic/documentation).

**Pull request closed without merging**
