### PR TITLE
Change References from Subsonic to Libresonic

### PR DESCRIPTION
**Pull request by csobsidian**
This patch is meant to address issue #42.

This covers most of the string usage of "Subsonic", specifically those found in the default strings of the SystemService and those found in the localization files. I only changed non-English files where they seemed appropriate due to a change in the English localization.

This patch also changes the logos in all themes to a dark or light version of a placeholder image with the text "Libresonic". These images are not meant to be permanent. Rather, they are a stepping stone to keep moving forward with a new brand and remove as many user-facing references to Subsonic as possible.

No changes have been made to other references of Subsonic, such as those found in copyright notices, references to the net.sourceforge.subsonic namespace, or references to the subsonic website.

### CODE REVIEW

**Comment by jooola** [comment]
But will they be any real logo ? ( something like a picture not only text ? )

**Comment by EugeneKay** [comment]
Wow, thank you very much! This is way more involved than I was going to be, so that's awesome. Regarding the internationalizations, what is the significance of the (escape code changes)[https://github.com/Libresonic/libresonic/pull/59/commits/bcd38255b963863d4456c4628b7038a0ca77bc8e#diff-bfd7a120b400970aac44573605edf450L173]? I believe those are unicode sequences; is this to more closely follow the standards? I just want to ensure that we don't break other languages.

I am fine with that for a temporary logo. I welcome more entries and voting in #43.

Can you add a --signoff --allow-empty commit to the PR to acknowledge GPLv3(new as of 95f1ed7)? I will test and merge this evening.

**Comment by csobsidian** [comment]
It looks like netbeans made all the escape code hex-characters lower-case: 00E1 becomes 00e1. I could not find a setting to leave them as they were.

**Comment by EugeneKay** [comment]
Let's stick with the uppercase hex-codes. It would be best if you could rebase the bad change away, or I can do it before merging.

**Comment by csobsidian** [comment]
I don't want to make extra work for you so I'll take care of it. I'm not very familiar with git or github so bear with me as I figure out the best way to go about it.

**Comment by csobsidian** [comment]
Mildly off-topic but I'd like to make sure I do this right. (I'm happy to delete this comment later) Will this work:

- New branch from develop.
- Cherry-pick the two good commits.
- Make changes to the serversettings and localization files
- Push to issue-42-patch

Will that push the fixed files to this PR?

**Comment by EugeneKay** [comment]
That would work correctly, yes.

Github PRs store the relationship between the two branches, meaning that any time you update issue-42-patch in your repo it will be updated here.

**Comment by csobsidian** [comment]
Okay, all fixed.

**Comment by EugeneKay** [comment]
That's fine, your acknowledgement here is good enough for me. Merge incoming.

**Pull request merged**
