### PR TITLE
Add Moment.js library

### PR DESCRIPTION
**Pull request by biconou**
This PR adds Moment JS library (https://momentjs.com/) for date and time manipulations.

### CODE REVIEW

**Comment by muff1nman** [comment]
What is this related to? Why split this out from the PR that needs this?

**Comment by biconou** [comment]
This is related to a work I am doing on jukebox UI. It's used to calculate song duration.
I propose it here as a general purpose library to manipulate dates. So I created a dedicated PR for that. 
It can be considered as part of some guideline (should be documented) for javascript development.

**Comment by muff1nman** [comment]
Makes sense and looks handy. But it doesn't make sense to merge this in by itself but as part of the jukebox PR.

**Comment by biconou** [comment]
Ok. I'll discard this PR.

**Pull request closed without merging**
