### PR TITLE
Fix remember me

### PR DESCRIPTION
**Pull request by muff1nman**

### CODE REVIEW

**Comment by muff1nman** [comment]
Addresses #151

**Comment by muff1nman** [comment]
@fxthomas Can you test by any chance?

**Comment by fxthomas** [comment]
I am afraid it doesn't work. I just checked the the `stable` branch to be sure : when I login with "remember me" then restart Libresonic, I stay logged in. This doesn't happen on `develop` even with this PR.

The docs mention adding a `RememberMeAuthenticationFilter` which supposedly handles these types of login requests, and this is where my knowledge of Spring stopped when I tried fixing it myself... Any other ideas?

**Comment by muff1nman** [comment]
I had set it up so remember me keys refresh during application startup, but will revert it to its previous behavior.

**Comment by muff1nman** [comment]
@fxthomas 409efd5 should get you the previous behavior.

**Comment by fxthomas** [comment]
Awesome, it works for me!

**Pull request merged**
