### PR TITLE
Set compiler to Java 1.8; updated some maven plugins

### PR DESCRIPTION
**Pull request by chetan**
Cleaned up the parent POM file a bit to get it to build cleanly on my machine. Also updated some basic maven plugins.

### CODE REVIEW

**Comment by EugeneKay** [comment]
For the .gitignore, please copy-paste an appropriate template from [github/gitignore](github.com/github/gitignore).

I'm unsure of the implications of moving up to Java 8 for compatibility. However, I'm also doubt that this is significant compared to the implications of running a JRE or system that old. Discussion welcomed.

The maven plugin update causes a build failure on my machine:

```
[eugene@wenatchee player (develop)]# rm ~/.m2/ -rf
[eugene@wenatchee player (develop)]# mvn -X -e package 2>&1 | tee mvn.log
<omitted for brevity>
[INFO] Compiling 61 source files to /home/eugene/code/libresonic/player/libresonic-rest-api/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Libresonic ........................................ SUCCESS [0.228s]
[INFO] Libresonic REST API ............................... FAILURE [19.300s]
[INFO] Sonos API ......................................... SKIPPED
[INFO] Libresonic Main ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.742s
[INFO] Finished at: Wed May 18 00:26:13 UTC 2016
[INFO] Final Memory: 11M/236M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project libresonic-rest-api: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project libresonic-rest-api: Fatal error compiling
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal error compiling
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:897)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.codehaus.plexus.compiler.CompilerException: invalid target release: 1.8
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:172)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:171)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:886)
        ... 22 more
Caused by: java.lang.IllegalArgumentException: invalid target release: 1.8
        at com.sun.tools.javac.main.RecognizedOptions$GrumpyHelper.error(RecognizedOptions.java:88)
        at com.sun.tools.javac.main.RecognizedOptions$10.process(RecognizedOptions.java:359)
        at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:242)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:199)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:68)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:124)
        ... 24 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :libresonic-rest-api
[eugene@wenatchee player (develop)]# java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
[eugene@wenatchee player (develop)]# yum info java-1.8.0-openjdk-headless
Loaded plugins: fastestmirror, remove-with-leaves
Loading mirror speeds from cached hostfile
 * base: linux.mirrors.es.net
 * epel: mirrors.cat.pdx.edu
 * extras: linux.mirrors.es.net
 * rpmforge: mirror.chpc.utah.edu
 * updates: linux.mirrors.es.net
Installed Packages
Name        : java-1.8.0-openjdk-headless
Arch        : x86_64
Epoch       : 1
Version     : 1.8.0.91
Release     : 0.b14.el7_2
Size        : 102 M
Repo        : installed
From repo   : updates
Summary     : OpenJDK Runtime Environment
URL         : http://openjdk.java.net/
License     : ASL 1.1 and ASL 2.0 and GPL+ and GPLv2 and GPLv2 with exceptions and LGPL+ and LGPLv2 and MPLv1.0 and MPLv1.1 and Public Domain and W3C
Description : The OpenJDK runtime environment without audio and video support.
[eugene@wenatchee player (develop)]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[eugene@wenatchee player (develop)]#
```

**Comment by csobsidian** [comment]
Builds for me.

~~~
------------------------------------------------------------------------
Reactor Summary:

Libresonic ........................................ SUCCESS [20.341s]
Libresonic REST API ............................... SUCCESS [12.377s]
Sonos API ......................................... SUCCESS [7.261s]
Libresonic Main ................................... SUCCESS [1:13.921s]
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 1:54.489s
Finished at: Tue May 17 18:53:59 PDT 2016
Final Memory: 42M/364M
------------------------------------------------------------------------

~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial

~$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
~~~

**Comment by chetan** [comment]
@EugeneKay It could be your version of maven is too old. Looks like it's 3.0.x on cent7. FWIW, I'm building on OS X and getting JDK6 is a no-go for me. JDK6 was shipped by Apple and they stopped supporting it several years ago. Can you try upgrading to maven 3.3 and see if that works?

**Comment by chetan** [comment]
Also I think my main issue was with how the repositories were configured. I can try rolling back the plugin versions and see if it still builds.

**Comment by EugeneKay** [comment]
I figured this out last night(mostly). My build system was missing the java-1.8.0-openjdk-devel package, which provides `javac` for JDK8(separate from the rest of the JDK.....). However, the build still failed because of an un-downloadable dependency. I have not checked yet today to see if that has been resolved.

**Comment by alexfornuto** [comment]
I just built the war on a Linode running openjdk-8. Would any of the logs or output help you guys?

**Pull request merged**
