### PR TITLE
Various documentation improvements

### PR DESCRIPTION
**Pull request by muff1nman**
- Remove duplicate and outdated INSTALL.md file
- Clarity around supported platforms
- Misc

Signed-off-by: Andrew DeMaria <lostonamountain@gmail.com>

### CODE REVIEW

**Comment by muff1nman** [comment]
Can someone read over? Thanks

**Comment by muff1nman** [comment]
The Configuration doc is currently missing, but I'll add that separately.

**Comment by jooola** [comment]
I starter build the libresonic wiki on the website ! They are maybe some useful informations ! I'll correct the outdated by the new zones when i''ll have time! And read you're doc too !
[https://github.com/libresonic/Libresonic.github.io](https://github.com/libresonic/Libresonic.github.io)

**Comment by zifnab06** [comment]
I don't see any glaring omissions, lgtm.

**Pull request merged**
