### PR TITLE
Losslessly recompress PNG files using ECT

### PR DESCRIPTION
**Pull request by ibmibmibm**
-- Removed, updated information is below.

### CODE REVIEW

**Comment by jooola** [comment]
Could you do this once #400 is merged ? Or add the changes once my PR is merged ?

**Comment by ibmibmibm** [comment]
sure

**Comment by jooola** [comment]
@ibmibmibm You need now to rebuild you're PR since #400 ( #421 ) has been merged.
New assets where build and this PR still have the old ones !

( This PR goes into develop )

**Comment by ibmibmibm** [comment]
Rebuilded.

**Comment by jooola** [comment]
Nice thanks ! I don't think we won lot of files size (load speed) but that's good anyway !

**Pull request merged**
