### PR TITLE
Install guide

### PR DESCRIPTION
**Pull request by alexfornuto**
I would prefer if someone would independently verify these instructions before it's merged.

### CODE REVIEW

**Comment by cdetroye** [comment]
## BUILD.md
I have tested a build from source and deployment and the install worked fine.

**Platform**: Ubuntu 14.04.3 LTS
**JDK**: OpenJDK 1.7.0_101
**Maven**: 2.2.1
**Tomact**: 6

I know you said OpenJDK 8 in the build.md **but it was most certainly not needed**. Tomcat 6 also works. I have not yet tested it with maven 1. 

I am a bit confused why the deployment step for Tomcat is mentioned in the BUILD.md file, though. That is deployment instead of building and it is missing the extra step of creating the required directories so that might confuse readers. Tomcat throws some error about the database file being locked while the initial error is the directory not existing.

A minor note is that the clone of the current master is still branded as subsonic and not libresonic. That should match up as well. Maybe add a `git checkout develop`

**Comment by m1dnight** [comment]
## BUILD.md
I have tested a build from source and deployment and the install worked fine.

**Platform**: Ubuntu 14.04.3 LTS
**JDK**: OpenJDK 1.7.0_101
**Maven**: 2.2.1
**Tomact**: 6

I know you said OpenJDK 8 in the build.md **but it was most certainly not needed**. Tomcat 6 also works. I have not yet tested it with maven 1. 

I am a bit confused why the deployment step for Tomcat is mentioned in the BUILD.md file, though. That is deployment instead of building and it is missing the extra step of creating the required directories so that might confuse readers. Tomcat throws some error about the database file being locked while the initial error is the directory not existing.

A minor note is that the clone of the current master is still branded as subsonic and not libresonic. That should match up as well. Maybe add a `git checkout develop`

edit: And finally, add that tomcat 6+ is a requirement.

**Comment by alexfornuto** [comment]
Thanks for the review @m1dnight! I gave the versions that I was using on my build case. Having your input, I'll adjust the range of versions. 

The contents of BUILD.md remain largely unchanged for now. It's the former INSTALL file, which I am preserving until my INSTALL is set up, after which I will look at trimming BUILD.

Finally, I'll adjust all references to Subsonic.

**Comment by uzantonomon** [comment]
I was reading the INSTALL.md file and the .WAR installation won't work if you create /var/libresonic. You have to create /var/subsonic. I'm using the Libresonic 6.0.1 and Tomcat 8.5.5.

**Comment by a9e78rauijasdf** [comment]
Tried deploying on 16.04 on a clean install. Fails - from catalina.out:

[2017-03-06 17:53:57,114] WARN  org.springframework.web.context.support.XmlWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.fac
tory.BeanCreationException: Error creating bean with name 'liquibase' defined in ServletContext resource [/WEB-INF/applicationContext-db.xml]: Invocation of init method failed; nested exception is liquibase.exc
eption.DatabaseException: java.sql.SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@497ae66d[file =/db/libresonic.lck, exists=false, locked=false, valid=false, fl
=null]: java.io.FileNotFoundException: /db/libresonic.lck (No such file or directory)
[2017-03-06 17:53:57,117] ERROR org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in ServletContext resource [/WEB-INF/applicationContext-db.xml]: Invocation of init method failed; nest
ed exception is liquibase.exception.DatabaseException: java.sql.SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@497ae66d[file =/db/libresonic.lck, exists=false, l
ocked=false, valid=false, fl =null]: java.io.FileNotFoundException: /db/libresonic.lck (No such file or directory)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
 
[etc]

**Pull request merged**
