### PR TITLE
Add keyboard shortcuts

### PR DESCRIPTION
**Pull request by fxthomas**
This PR is a work in progress towards adding keyboard shortcuts to Libresonic as discussed in #101. It's mostly a port of what was available in Subsonic 6.0-beta1, but I'd love to get feedback on how this is implemented.

Right now, the plan is to :
- [x] Add the same keyboard shortcuts as Subsonic (to avoid confusing users when they switch)
- [x] Test that JWPlayer behaves correctly
- [ ] Test that the Cast player behaves correctly
- [x] Test that the Jukebox player behaves correctly
- [x] Add a user option under the _Settings_ > _Personal_ page to enable/disable shortcuts
- [x] Add a help page that explains which keyboard shortcuts are available

### CODE REVIEW

**Comment by fxthomas** [comment]
I've been meaning to ask this as well : is it okay to add a `togglePlayPause` method to both `CastPlayer` to the Jukebox REST API? I'm currently determining the play status by hand with the play/pause shortcut, which is at best unreliable, esp. for the Jukebox player.

**Comment by fxthomas** [comment]
Work on this should be pretty much done, and I tested it on both the in-browser player and Jukebox mode.

The keyboard icon is the help page is pretty ugly, so if you are okay with bringing `font-awesome` in I can change it. Also shortcuts "should" work in ChromeCast mode (the code is there), but I don't have a device that supports casting so I did not test it at all.

**Comment by EugeneKay** [comment]
Wow, this is huge. I will merge it into develop after 6.1 and we'll see how it goes.

**Comment by fxthomas** [comment]
Perfect!

If we continue to follow the same conventions re: naming DB migrationn classes, they will need to be renamed for 6.2 once 6.1 is released. I'm currently running this on my server so I'll update the PR then.

**Comment by fxthomas** [comment]
FYI : just rebased this onto `develop`.

**Comment by plastikman** [comment]
Thank you for this @fxthomas I absolutely love them!

**Comment by alexfornuto** [comment]
Where can someone see the shortcuts without going through the code itself?

**Comment by fxthomas** [comment]
@alexfornuto Either press the '?' key or go to the "More" page (link on the top bar).

@plastikman Thanks :)

**Comment by plastikman** [comment]
@alexfornuto I just noticed that in the documentation the keybinding icon to change songs in an arrow pointing up, the arrow should be pointing to the right.

http://imgur.com/a/tvFDx

**Comment by fxthomas** [comment]
Hum, thanks for noticing! :)

**Comment by plastikman** [comment]
in libresonic-main/src/main/webapp/WEB-INF/jsp/more.jsp
the code at line 219 needs to change from 
`<td class="more-shortcut">&#8593;</td><td class="more-shortcut-descr"><fmt:message key="more.keyboard.next"/></td>`
to 
`<td class="more-shortcut">&#8594;</td><td class="more-shortcut-descr"><fmt:message key="more.keyboard.next"/></td>`

**Pull request merged**
