### PR TITLE
Remove installation from project

### PR DESCRIPTION
**Pull request by muff1nman**
Removes the booter, assembly, and installation submodules. There may still be some value in these deleted files, but it is expected that any packages will be moved to a different repository under the libresonic org.

In addition, I have removed the ability to change the port and context path as these should now be done either via tomcat or via spring boot. It may make sense to present options to change these like how we did in libresonic.sh, but again it should be done via spring boot at that point and not done in the main codebase.

### CODE REVIEW

**Comment by biconou** [comment]
I think the libresonic-assembly is still usefull. It contains the shells.

**Comment by muff1nman** [comment]
The shell scripts themselves might be useful, but libresonic-assembly itself is useless as the only artifact needed is the libresonic.war built in libresonic-main. At any rate, we could salvage the shells out to a different repo along with the other os-specific things later.

**Comment by biconou** [comment]
Indeed. Since these other repos are not yet created, should'nt we store the shells anywhere else (for example in the documentation).
What about the libresonic-tools subproject ? It seams to be outdated too.

**Comment by muff1nman** [comment]
I believe I did remove the tools directory. We can always go back in the history to look at the shell scripts.

**Comment by EugeneKay** [comment]
@biconou @muff1nman Let me know if you'd like a separate libresonic-tools repo

**Comment by biconou** [comment]
That could be usefull. Nice proposition.

**Pull request merged**
