### PR TITLE
Spring 3 and Spring Security

### PR DESCRIPTION
**Pull request by muff1nman**
Although there is still work to be done to get to spring 4, I feel like spring 3 and migrating to spring security is a good milestone. See #80

### CODE REVIEW

**Comment by biconou** [comment]
I tested this PR. It seems to work.
What must be done more ?

**Comment by muff1nman** [comment]
Just needs review/testing and thanks for taking a look. There are a couple things to be done as listed in #80 but I think they can be done as we have time/see fit and shouldn't delay this any further. I think I wont merge this for a day or so to see if anyone else wants to review/test/merge it.

**Comment by biconou** [comment]
I don't like the multiController (org.libresonic.player.controller.MultiController). It seems to be a messy multi-purpose controller thats serves multiple pages. What about splitting it in several specialized controllers ?

**Comment by biconou** [comment]
What about moving the Spring configuration to annotation style ?

**Comment by biconou** [comment]
In each xml Spring context file, the beans declaration still references the 2.5 version.

```
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">
```
It seems ok to replace 
http://www.springframework.org/schema/beans/spring-beans-2.5.xsd 
by
http://www.springframework.org/schema/beans/spring-beans.xsd

**Comment by biconou** [comment]
May be there is some kind of problem with Spring Security. 
Here is the test case : 
Login Admin
I add a media folder (say music).
I scan the medias.
When I click on any artist name in the left frame, I got a message 

> Access denied
> Sorry, you are not authorized to perform the requested operation. 

Looking at the Admin user settings I can see that this user is granted to the music media folder.

**Comment by muff1nman** [comment]
Would love to replace multi controller, just didn't get around to it.
Moving to annotation config is fine, I just didn't see it as terribly important.
Bumping the beans xsd is a good idea, that probably needs to be done.

**Pull request merged**
