### PR TITLE
Updating Haproxy documentation

### PR DESCRIPTION
**Pull request by jooola**
I tested the old configuration but i wanted to simplify the configuration file !

### CODE REVIEW

**Comment by fxthomas** [comment]
The goal for this documentation is that we can provide a working configuration that people can safely copy-paste and expect to work with the minimum amount of changes, even if they're not familiar with HAProxy (which is my case, incidentally).

So, two things :

* I'm thinking we should at least mention `mode http` somewhere. It wasn't the default when I worked on #242, so people new to HAProxy can forget or accidentally delete it from the configuration. I'm fine with adding a `default` section though, at least it's explicit!
* The text above the configuration mentions "HTTP → HTTPS redirection". Is that still the case after removing the `ssl_fc` check? If not the text should be updated to say e.g. "HTTP and HTTPS".

**Comment by jooola** [comment]
Yeah sure, but want to prevent having 2 same line in the configuration files, but you're right i'll add a default section !

We could keep the "forcing https" lines as an option ! This is best i think !

I'll correct those 3 lines !

**Comment by fxthomas** [comment]
Awesome! As far as I am concerned this can be merged then :)

**Comment by jooola** [comment]
Great, i'll do some others cosmetic !

**Pull request merged**
