### PR TITLE
Change logo and icons Fix #192 and #263

### LINKED ISSUE #192: New logo uses non-free fonts
Looks like the new logo is using [DIN Condensed](http://www.paratype.com/pstore/default.asp?fcode=PT_DNC&letter=D) which is a non-free font.

There may be some alternatives: [Alte Din](http://www.1001fonts.com/alte-din-1451-mittelschrift-font.html) or [Cabin](https://fonts.google.com/specimen/Cabin+Condensed?selection.family=Cabin|Cabin+Condensed)

I tried updating the logo with these, but my svg skills aren't the best - I couldn't quite achieve the same look: 

logo_dark svg
logo_light svg

the first is Cabin and the second in Alte Din.

### PR DESCRIPTION
**Pull request by jooola**
Fix #192 and #263

### CODE REVIEW

**Comment by muff1nman** [comment]
This is missing some files I think:
- contrib/assets/logo-square_dark.svg
- contrib/assets/logo-square_light.svg
- contrib/assets/logo_dark.svg
- contrib/assets/logo_light.svg

**Comment by muff1nman** [comment]
Nevermind that last comment, they were deleted.

**Comment by jooola** [comment]
Yes, note that i build the SVG by converting the PNG files. So they are a bit more heavy...
I didn't know how to use Inkscape to reproduce the exact same pictures.

**Comment by muff1nman** [comment]
Inkscape should be able to save the SVG's directly, it would be good to see if you can get these originals so we can resize images later.

**Comment by jooola** [comment]
I meant that i could not reproduce the pictures using Inkscape, since i really don't know how to use this software !

I used Inkscape to import the PNG files and then save to SVG.
So if you see the SVG files they are heavier than the same pictures build from scratch ( using Inkscape ).

I may not understand your last comment but :  
* If you're looking for the originals i uploaded all the pictures in xcf ( gimp ) and png, with a really decent resolution.
* If you're talking about using the old SVG's with nonfree fonts i don't get why ?!

**Comment by muff1nman** [comment]
Ideally I would have liked to see svgs either made from the original or made from scratch. They scale better.

**Pull request merged**
